openapi: 3.0.0
info:
  title: GeoQuery Demo APIs
  description: Demo apis
  version: 1.0.2
servers:
  - url: 'https://virtserver.swaggerhub.com/ShubhamShewdikar/GeoQuery-demo-apis/1.0.0'
paths:
  /geocode:
    get:
      summary: Geocode the address
      description: 'By passing in the appropriate address for geocoding, address will be converted into latitude and longitude'
      parameters:
        - name: address
          in: query
          description: address for geocoding
          required: true
          style: form
          explode: true
          schema:
            type: string
          example: 'Ideas to Impacts Building Lane 3, Baner Rd, Pallod Farms, Baner, Pune, Maharashtra 411045'
        - name: city
          in: query
          description: city of an address
          required: true
          style: form
          explode: true
          schema:
            type: string
          example: Pune
        - name: pinCode
          in: query
          description: pinCode of an address
          required: true
          style: form
          explode: true
          schema:
            $ref: '#/components/schemas/geocodingInput'
          example: 411045
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/geocodingOutput'
              examples:
                Geocoding Result:
                  value:
                    - latitude: 18.5568147
                      longitude: 73.79745869999999
                      geoAccuracy: Rooftop
                      inputAuality: Medium
                      cityPincodeMatch: true
        '400':
          description: 'invalid input, object invalid'
        '500':
          description: Internal Server Error
  /negativeArea:
    get:
      summary: To check if latitude and longitude is in Negative Area
      description: By passing in the appropriate latitude and longitude as a input in query string parameters will check if its fall in a negative area
      parameters:
        - name: latitude
          in: query
          description: latitude
          required: true
          style: form
          explode: true
          schema:
            type: number
          example: 19.0455145
        - name: longitude
          in: query
          description: longitude
          required: true
          style: form
          explode: true
          schema:
            $ref: '#/components/schemas/negativeAreaInput'
          example: 10
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/negativeAreaOutput'
              examples:
                Negative Area Result:
                  value:
                    - isInNegativeArea: true
                      latitude: 18.5568147
                      longitude: 73.79745869999999
        '400':
          description: 'invalid input, object invalid'
        '500':
          description: Internal Server Error
components:
  schemas:
    geocodingInput:
      required:
        - address
        - city
        - pinCode
      type: object
      properties:
        address:
          type: string
          description: Address string of the location
          example: 'Ideas to Impacts Building Lane 3, Baner Rd, Pallod Farms, Baner, Pune, Maharashtra 411045'
        city:
          type: string
          description: City string of the location
          example: Pune
        pinCode:
          type: number
          description: Pincode number of the location
          example: 411045
    geocodingOutput:
      type: object
      properties:
        latitude:
          type: number
          example: 18.5568147
        longitude:
          type: number
          example: 73.79745869999999
        geoAccuracy:
          type: string
          example: Rooftop
        inputQuality:
          type: string
          example: Medium
        cityPincodeMatch:
          type: boolean
          example: true
    negativeAreaInput:
      required:
        - latitude
        - longitude
      type: object
      properties:
        latitude:
          type: number
          description: latitude from geocoding output object
        longitude:
          type: number
          description: longitude from geocoding output object
    negativeAreaOutput:
      type: object
      properties:
        isInNegativeArea:
          type: boolean
          example: true
        latitude:
          type: number
          example: 18.5568147
        longitude:
          type: number
          example: 73.79745869999999
  securitySchemes:
    x-api_key:
      type: apiKey
      name: API Key
      in: header
