openapi: 3.0.0
info:
  title: files
  version: '1.0'
  description: API for Files
  contact:
    name: Magnetic Asia
    url: 'https://www.magneticasia.com/'
    email: info@magneticasia.com
  termsOfService: 'https://www.magneticasia.com/terms-conditions.html'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'https://magneticasia.stoplight.io/mocks/magneticasia/openapi-sessions/336833'
    description: Stoplight Mock Server
tags:
  - name: Files API
    description: Files CRUD and related stuff.
paths:
  /files/images:
    get:
      summary: get-images
      tags:
        - Files API
      responses:
        '200':
          description: OK
      operationId: get-images
      description: GET Images
    post:
      summary: Post Image
      operationId: post-image
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
              examples:
                example-1:
                  value:
                    status: success
      description: POST Image
      parameters:
        - schema:
            type: string
            pattern: application/json; version=1
          in: header
          name: Accept
          required: true
        - schema:
            type: string
            pattern: ^(en|zh-hant|zh-hans|ja|ko)$
          in: header
          name: Accept-Language
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: uri
              required:
                - file
        description: ''
      tags:
        - Files API
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: JWT
