openapi: 3.0.0
info:
  title: files
  version: '1.0'
  description: API for Files
  contact:
    name: Magnetic Asia
    url: 'https://www.magneticasia.com/'
    email: info@magneticasia.com
  termsOfService: 'https://www.magneticasia.com/terms-conditions.html'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'https://magneticasia.stoplight.io/mocks/magneticasia/openapi-sessions/336833'
    description: Stoplight Mock Server
tags:
  - name: Files API
    description: Files CRUD and related stuff.
paths:
  /files/images:
    get:
      summary: get-images
      tags:
        - Files API
      responses:
        '200':
          description: OK
      operationId: get-images
      description: GET Images
    post:
      summary: Post Image
      operationId: post-image
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  relative_path:
                    type: string
                    example: success
                  origin:
                    type: string
              examples:
                example-1:
                  value:
                    relative_path: /640/480/abstract
                    origin: 'http://lorempixel.com'
      description: POST Image
      parameters:
        - schema:
            type: string
            pattern: application/json; version=1
          in: header
          name: Accept
          required: true
        - schema:
            type: string
            pattern: ^(en|zh-hant|zh-hans|ja|ko)$
          in: header
          name: Accept-Language
      tags:
        - Files API
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
              format: binary
            examples:
              example-1:
                value: string
        description: ''
  /files/pdfs:
    get:
      summary: get-pdfs
      tags:
        - Files API
      responses:
        '200':
          description: OK
      operationId: get-pdfs
      description: GET PDFs
    post:
      summary: Post PDF
      operationId: post-pdf
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  relative_path:
                    type: string
                    example: success
                  origin:
                    type: string
              examples:
                example-1:
                  value:
                    relative_path: /media/images/alpha.png
                    origin: 'https://www.alpha.com'
      description: POST PDF
      parameters:
        - schema:
            type: string
            pattern: application/json; version=1
          in: header
          name: Accept
          required: true
        - schema:
            type: string
            pattern: ^(en|zh-hant|zh-hans|ja|ko)$
          in: header
          name: Accept-Language
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: uri
              required:
                - file
            examples:
              example-1:
                value:
                  file: 'data:application/pdf;base64,JVBERi0xLjQKJcOIw4HDhMOXDQo4IDAgb2JqCjw8Ci9GaWx0ZXIgL0ZsYXRlRGVjb2RlIAovTGVuZ3RoIDEyMSAKPj4gc3RyZWFtCnicVYuxCsIwFEX3fsUZ06HxvdrktasgiJuQTdxMdYgUM+jvWxdBLtx77nB4In6M9tf1hn1JsXUnCwxh64NGOhPxqgM1M3Nq2CU2h1xeaE='
        description: ''
      tags:
        - Files API
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: JWT
