openapi: 3.0.0
info:
  title: sessions
  version: '1.0'
  description: API for User Signup/Signin
  contact:
    name: Magnetic Asia
    url: 'https://www.magneticasia.com/'
    email: info@magneticasia.com
  termsOfService: 'https://www.magneticasia.com/terms-conditions.html'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'https://magneticasia.stoplight.io/mocks/magneticasia/openapi-sessions/1646925'
    description: Stoplight Mock Server
tags:
  - name: Sessions API
    description: Sessions CRUD and related stuff.
paths:
  /session-event-types:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Type - Alpha
              examples:
                example-1:
                  value:
                    - name: Type - Alpha
                    - name: Type - Bravo
      operationId: get-session-event-types
      description: Get the list of session-event types.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: The JWT/Bearer token.
          required: true
  /session-event-categories:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Type - Alpha
                    sub-categories:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
              examples:
                example-1:
                  value:
                    - name: Category - Alpha
                      sub-categories:
                        - name: Sub-Category - Alpha 1.1
                    - name: Category - Bravo
                      sub-categories:
                        - name: Sub-Category - Bravo 1.1
                        - name: Sub-Category - Bravo 1.2
                    - name: Category - Charlie
                      sub-categories: []
      operationId: get-session-event-categories
      description: Get the list of session-event categories.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: The JWT/Bearer token.
          required: true
  /organisation-name:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
              examples:
                example-1:
                  value:
                    name: Organisation - Alpha
      operationId: get-organisation-name
      description: Get the organisation name of the user.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: The JWT/Bearer token.
          required: true
