openapi: 3.0.0
info:
  title: sessions
  version: '1.0'
  description: API for User Signup/Signin
  contact:
    name: Magnetic Asia
    url: 'https://www.magneticasia.com/'
    email: info@magneticasia.com
  termsOfService: 'https://www.magneticasia.com/terms-conditions.html'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'http://localhost:3000'
    description: Local
tags:
  - name: Sessions API
    description: Sessions CRUD and related stuff.
paths:
  /session-event-types:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Type - Alpha
              examples:
                example-1:
                  value:
                    - name: Type - Alpha
                    - name: Type - Bravo
      operationId: get-session-event-types
      description: Get the list of session event types.
