openapi: 3.0.0
info:
  title: user
  version: '1.0'
  description: API for User Signup/Signin
  contact:
    name: Magnetic Asia
    url: 'https://www.magneticasia.com/'
    email: info@magneticasia.com
  termsOfService: 'https://www.magneticasia.com/terms-conditions.html'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'http://localhost:3000'
    description: Local
tags:
  - name: User API
    description: User Signip/Signin
